# 自动测试

## 前言

- 1972年 Edsger W.Dijkstra 说：程序测试可以有效的发现 bug 的存在，但是却不可能证明 bug 的不存在
- Rust 的类型系统在很大程度上确保了程序数据的正确性，但是却无法保证程序运行的逻辑是我们所预期的
- 例如，有一个 function，接收一个 int 参数，并为该参数加上 2 以后返回，那么 rust 的类型系统可以确保程序运行时传入和返回的数据都是 int 而不是其它（例如 String），但是 rust 却无法保证我们的程序逻辑是否确实对输入参数正确进行了加上 2 的操作
- 因此这就是 test 的作用，通过编写 test 来测试和验证

# 11.1 How to Write Tests

test 是 rust 中的 function，用来验证其它非 test 的代码是否按照预期执行，因此，test function 内一般做如下几件事：
1. 建立测试所需的 data 或 state
2. 运行要测试的代码
3. 确认结果是否符合预期

### The Anatomy of a Test Function

我们通过新建一个 lib 项目来看 test function 内部的细节：
```text
cargo new teststh --lib
```

然后来剖析 ```src/lib.rs``` ：
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

##### ```#[test]```

- 用来标识这是一个 test function
- 对应的是下面的 ```fn it_works```
- 该 function 可以自己编写并命名，包括使用参数、返回值等
- 目前该代码中使用了 ```assert_eq!``` 这个 macro 来检查两份数据是否相等
- 可以有很多个 test function，只要有 ```#[test]``` 标识即可
- 要运行这些 test function，需要执行命令 ```$ cargo test```

##### ```$ cargo test```

- 通过执行该命令，来运行 test function
- 只要被 ```#[test]``` 标识过的 function，都会被执行

执行 ```$ cargo test``` 以后，下面是执行结果的例子：
```text
running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests ltsth1

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

- ```running 1 test``` ，提示有多少个 test function，就是 ```#[test]``` 标注的 function
- ```test tests::it_works ... ok``` ，这是其中一个 test function 的执行结果，包括了 module 名称，function 名称，以及执行的结果是 ok 还是 fail
- ```test result``` ，对测试结果进行统计，包括 ```passed``` ,  ```failed``` , ```ignored``` , ```measured``` , ```filtered out```
- 其中，```measured``` 是针对 ***benchmark test***，也就是只可用于 ***nightly rust*** 的版本
- ```Doc-tests``` 是针对 ***documentation test*** ，在 Chapter14 介绍

### Check Result with ```assert!```

- ```assert!``` 是一个 macro
- 需要传入一个参数，类型是 Boolean
- 如果传入 true，则测试通过，否则执行 ```panic!```

例如，增加 lib 的一些功能：定义 Rect，并编写 method 来判断能否容纳参数所传入的另一个 Rect ：
```rust
#[derive(Debug)]
struct Rect {
    width: u32,
    height: u32,
}

impl Rect {
    fn can_hold(&self, other: &Rect) -> bool {
        self.width > other.width && self.height > other.height
    }
}
```

> 注意，由于例子程序中，test function 在独立的一个 module 中，因此编写 test function 时，如果要使用外部定义的类型和方法，需要在 ```mod tests``` 内使用 ```use super::*;```

然后编写 test function，目的是确认一个大的 Rect 能够容纳小的 Rect ，测试通过：
```rust
#[test]
fn larger_can_hold_smaller() {
    let larger = Rect { width: 8, height: 7 };
    let smaller = Rect { width: 5, height: 1 };

    assert!(larger.can_hold(&smaller));
}
```

再编写一个 test function，目的是确认一个小的 Rect 不能容纳大的 Rect ，测试通过：
```rust
#[test]
fn smaller_cannot_hold_larger() {
    let larger = Rect { width: 8, height: 7 };
    let smaller = Rect { width: 5, height: 1 };

    assert!(!smaller.can_hold(&larger));
}
```

下面尝试将我们的代码改出 bug ，例如改动 ```can_hold``` 的判断逻辑：
```rust
fn can_hold(&self, other: &Rect) -> bool {
    self.width < other.width && self.height > other.height
}
```

则测试失败，可以读一读下面的失败信息：
```text
running 2 tests
test tests::smaller_cannot_hold_larger ... ok
test tests::larger_can_hold_smaller ... FAILED

failures:

---- tests::larger_can_hold_smaller stdout ----
thread 'tests::larger_can_hold_smaller' panicked at 'assertion failed: larger.can_hold(&smaller)', src/lib.rs:23:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    tests::larger_can_hold_smaller

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### Check Equality with ```assert_eq!``` and ```assert_ne!```

- 可以使用 ```assert!``` 并在此 macro 内通过 ```==``` 和 ```!=``` 来确认两份数据相等或不相等，因为 ```assert!``` 只能接受一份 Boolean 数据
- 但 ```assert_eq!``` and ```assert_ne!``` 使用起来更方便一些，接受两份数据，分别叫做 ***left*** 和 ***right***
- ```assert_eq!``` 是 equal
- ```assert_ne!``` 是 not equal
- 需要注意的是，```assert_eq!``` 和 ```assert_ne!``` 内部使用的是 ```==``` 和 ```!=``` ，而且，如果检查失败，会打印出 ***left*** 和 ***right*** 的内容
- 这就决定了 ***left*** 和 ***right*** 需要实现 ```PartialEq``` 和 ```Debug``` 这两个 trait
- 但是 ```PartialEq``` 和 ```Debug``` 都是可以 derive 的，因此简单起见，可以在我们的数据类型上直接使用 ```#[derive(PartialEq, Debug)]```

例如，实现一个 function，功能是将传入的数据加 2 并返回：
```rust
pub fn add_two(a: i32) -> i32 {
    a + 2
}
```

然后编写 test function ，测试通过：
```rust
#[test]
fn really_adds_two() {
    assert_eq!(4, add_two(2));
}
```

然后将代码改出 bug ：
```rust
pub fn add_two(a: i32) -> i32 {
    a + 3
}
```

则测试失败，下面是部分失败信息，可以看到 ***left*** 和 ***right*** 的值被打印出来了：
```text
thread 'tests::really_adds_two' panicked at 'assertion failed: `(left == right)`
left: `4`,
right: `5`', src/lib.rs:12:9
```

### Adding Custom Failure Messages

- 前面内容介绍的 ```assert!``` , ```assert_eq!``` , ```assert_ne!``` 内部都使用了 ```panic!```
- 而实际上，```panic!``` 是可以自定义的错误信息的
- 因此，```assert!``` , ```assert_eq!``` , ```assert_ne!``` 也可以自定义错误信息，且该错误信息会传递给 ```panic!```
- 从而，当测试失败时，自定义的错误信息就会通过 ```panic!``` 被显示出来，便于我们查找错误发生的位置
- 自定义错误信息的用法与 ```format!``` 类似

下面是语法举例：
```rust
let i = 5;
let j = 6;
assert!(i == j, "i({}) != j({})", i, j);
assert_eq!(i, j, "i({}) != j({})", i, j);
assert_ne!(i, j, "i({}) == j({})", i, j);
```

### Use ```panic!``` in Test Functions

- 前面内容介绍的 ```assert!``` , ```assert_eq!``` , ```assert_ne!``` 内部都使用了 ```panic!```
- 我们自己也可以在 test function 中使用 ```panic!```

例如下面最简单的例子：
```rust
#[test]
fn test_panic() {
    panic!("just panic");
}
```

则测试失败，下面是部分失败信息，可以看到 ```panic!``` 信息也打印出来了：
```text
running 1 test
test tests::test_panic ... FAILED

failures:

---- tests::test_panic stdout ----
thread 'tests::test_panic' panicked at 'just panic', src/lib.rs:7:9
```

### Checking for Panics with ```should_panic```

- 从前面的内容来看，如果测试过程中（不管是 test 代码还是非 test 代码）出现 panic ，则认为测试失败
- 但对于某些需求来说，程序 panic 是预期的行为
- 因此，```should_panic``` 的作用是用来说明 "此时程序 panic 是正确的"，从而出现 panic 时，也认为测试通过
- 但是，panic 可能是非预期的代码 bug 导致，也可能是预期的失败情况导致，而测试的目的，是要找出非预期的代码 bug
- 因此，可以为 ```should_panic``` 增加 ```expected``` 属性，格式为：```#[should_panic(expected = "sth")]```
- 而 ```"sth"``` 文本的内容，就是 ```panic!``` 中所附带的信息的 substring
- 因此，```should_panic``` 能否真正过滤掉预期错误的 panic ，取决于 ```expected``` 内容的精确性，且该内容只能截取 ```panic!``` 中固定不变的部分

例如，编写一个 function，判断传入的 int 值是否在 1-100 范围内，如果不满足条件，则 ```panic!``` 并输出错误信息：
```rust
pub fn range_1_to_100(a: i32) {
    if a >= 1 && a <= 100 {
    	return;
    }

    panic!("{} is not between 1-100", a);
}
```

然后在 test function 中，传入大于 100 的值，并在 ```should_panic``` 的 ```expected``` 属性里截取了错误信息中的固定内容，因此该 test function 的结果是 ```passed```：
```rust
#[test]
#[should_panic(expected = "is not between 1-100")]
fn greater100() {
	range_1_to_100(200);
}
```

尝试更改该 test function 的 ```expected``` 内容，发现测试结果是 ```failed``` （当然，这是 test function 本身导致的失败，并不是被测试代码的 bug）：
```rust
#[test]
#[should_panic(expected = "is is not not between 1-100")]
fn greater100() {
	range_1_to_100(200);
}
```

### Using ```Result<T, E>``` in Tests

- 可以设置 test function 的返回值类型为 ```Result<T, E>```
- 从而在执行测试时，会自动检查 test function 的返回值，如果返回 ```Ok<T>``` ，则测试通过，如果返回 ```Err<E>``` ，则测试失败，并打印出 ```E``` 的内容

例如，test function 返回成功，因此测试通过：
```rust
#[test]
fn use_result() -> Result<(), String> {
	Ok(())
}
```

又如，test function 返回错误，则测试失败，并打印出了失败信息：
```rust
#[test]
fn use_result() -> Result<(), String> {
    Err(String::from("result is Err"))
}
```

##### 进一步思考

- 需要注意的是，对于返回值为 ```Result<T, E>``` 的 test function，是不能通过 ```#[should_panic]``` 来标注的，当然，我们也不需要，因为只要 test function 返回 ```Err<E>``` ，测试结果就会失败，并自动打印出 ```E``` 的内容
- 但是，如果被测试的代码返回值类型是 ```Result<T, E>``` ，在 test function 中就可以很方便的使用 ```?``` , ```unwrap()``` 等，从而只关注成功结果，因为失败结果 ```E``` 会被自动传给 ```panic!```
- 同时，针对 ```Err<E>``` ，可以通过 ```#[should_panic]``` 来筛选是否属于预期错误

下面举个例子，如果传入的 int 数据在 1-100 范围内，则返回 ```Ok<T>``` ，否则返回 ```Err<E>``` ：
```rust
pub fn range_1_to_100(a: i32) -> Result<(), String> {
    if a >= 1 && a <= 100 {
    	return Ok(());
    }

    Err(String::from(format!("{} is not between 1-100", a)))
}
```

然后编写 test function，传入大于 100 的值，并使用 ```unwrap()``` ，同时配置 ```#[should_panic]``` 的 ```expected``` 属性，因此测试通过：
```rust
#[test]
#[should_panic(expected = "is not between 1-100")]
fn greater100() {
	range_1_to_100(200).unwrap();
}
```

# 11.2 Controlling How Tests Are Run

##### ```cargo test``` 默认行为

1. 运行所有 test function （ignore 的除外）
2. 使用并行方式同时运行所有 test function，因此要注意 test function 不能相互依赖，或依赖于共享的 data,state,environment 等
3. 对于成功的 test function，所有的标准输出都会被屏蔽，只显示测试结果为成功
4. 对于失败的 test function，标准输出不会被阻止

##### 关于 ```cargo test``` 的控制

- 类似于 ```cargo run``` 会编译并运行 binary 文件， ```cargo test``` 也是将测试代码编译为 binary 文件并运行，因此可以为 ```cargo test``` 指定命令行参数
- 参数分为两类，一类是针对 ```cargo test``` ，叫做 ```[OPTIONS]``` ，一类是针对测试的 binary 文件，叫做 ```[ARGS]```
- 参数都是用 ```--para``` 来指定，顺序是：```cargo test [OPTIONS] [TESTNAME] -- [ARGS]``` ，也就是说，通过 ```--``` 分隔，来表示后续的参数是 ```[ARGS]```
- 本章内容暂时不涉及到 ```[OPTIONS]``` ，主要针对 ```[TESTNAME]``` 和 ```[ARGS]```

### 使用 ```[ARGS]```

##### 显示标准输出 ```--nocapture```

下面的例子有两个 test function ，都会产生标准输出，但是一个成功，一个失败，可以看到只有失败的 test function 会打印标准输出：
```rust
fn ptsth(s: &str) {
	println!("{}", s);
}

#[cfg(test)]
mod tests {
	use super::*;

    #[test]
    fn test_func1() {
    	ptsth("func1");
        assert_eq!(2 + 2, 4);
    }

    #[test]
    fn test_func2() {
    	ptsth("func2");
        assert_eq!(2 + 3, 6);
    }
}
```

因此，如果针对成功的 test function 也要打印标准输出，则使用 ```--nocapture``` ，因此针对上面的例子，看到执行结果可能如下（节选了部分）：
```text
$ cargo test -- --nocapture

running 2 tests
func1
func2
thread 'tests::test_func2' panicked ...
test tests::test_func1 ... ok
test tests::test_func2 ... FAILED

failures:
    tests::test_func2

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

从上面的输出可以看到：
1. 成功和失败的 test function ，标准输出都被打印出来了
2. 但是，多个 test function 的输出显示是交错的，这是因为默认多个 test function 是并行执行的

##### 控制执行顺序 ```--test-threads```

说明：
- 从上面的例子看到，```cargo test``` 默认对于多个 test function 是并发执行的
- ==也可以理解为，如果有 N 个 test function，则有 N 个线程同时执行==
- 因此，通过 ```--test-threads``` ，可以控制测试执行时的线程数量
- 语法：```--test-threads=X```
- ```X``` 就是要设置的线程数量，如果为 1 ，就是串行执行各个 test function
- 如果 ```X``` 大于 1 ，则可以理解为设置了线程池，各个 test function 的执行工作自动分派到线程池调度执行
- 甚至允许 ```X``` 大于 test function 的数量，但 ```cargo test``` ==可能会自动将线程池的线程个数优化为不超过 test function 的数量==

例如，针对上面的例子，要求标准输出，同时串行执行，则得到的执行结果如下（节选了部分），可以看到，执行顺序是串行的：
```text
$ cargo test -- --nocapture --test-threads=1

running 2 tests
test tests::test_func1 ... func1
ok
test tests::test_func2 ... func2
thread 'main' panicked...
FAILED

failures:
    tests::test_func2

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### 使用 ```[TESTNAME]```

##### 黑名单 - 使用 ```ignore```

说明：
- 可以配置 test function 为 ```ignore``` ，从而 ```cargo test``` 就不执行这些 test function
- 语法：将 ```#[ignore]``` 配置在 ```#[test]``` 下面
- ***可以理解为针对 test function 的黑名单功能***

举例：
```rust
#[cfg(test)]
mod testm1 {

    #[test]
    #[ignore]
    fn test_1() {}

    #[test]
    fn test_2() {}
}
```

则执行结果节选如下，可以看到哪些 test function 被 ignore ，且在最后的结果统计中，看到被 ignore 的数量：
```text
running 2 tests
test testm1::test_1 ... ignored
test testm1::test_2 ... ok

test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```

##### 白名单 - 使用 ```filter```

规则说明：
- 可以指定 ```[TESTNAME]``` ，来实现哪些 test function 需要被 ```filter```
- 指定的 ```[TESTNAME]``` 是 test function 的 substring ，具有该 substring 的test function 会被执行，反之则被 ```filter```
- 需要注意的是：```[TESTNAME]``` 包括了 module 名称 和 function 名称，即 ```module1::module2::function1```
- ***可以理解为针对 test function 的白名单功能***

因此，通过指定 ```[TESTNAME]``` ，可以实现几种 ```filter``` ：
1. 指定为空，即不指定，则执行全部 test function
2. 指定为全称，或者唯一的名称，则只执行一个 test function
3. 指定部分名称，则执行具有该 substring 的系列 test function

下面通过一系列例子来展示 ```filter``` 的使用，首先是 test function 的代码如下；
```rust
#[cfg(test)]
mod testm1 {

    #[test]
    fn test_1() {}

    #[test]
    fn test_2() {}

    #[test]
    fn test_3() {}

    #[test]
    fn test_sth() {}
}

#[cfg(test)]
mod testm2 {

    #[test]
    fn test_1() {}

    #[test]
    fn test_2() {}

    #[test]
    fn test_3() {}

    #[test]
    fn test_sth() {}
}
```

> cargo test

```text
running 8 tests
test testm1::test_1 ... ok
test testm1::test_2 ... ok
test testm1::test_3 ... ok
test testm1::test_sth ... ok
test testm2::test_1 ... ok
test testm2::test_2 ... ok
test testm2::test_3 ... ok
test testm2::test_sth ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

> cargo test test_sth

```text
running 2 tests
test testm1::test_sth ... ok
test testm2::test_sth ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out
```

> cargo test testm2

```text
running 4 tests
test testm2::test_1 ... ok
test testm2::test_2 ... ok
test testm2::test_3 ... ok
test testm2::test_sth ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out
```

> cargo test testm1::test_1

```text
running 1 test
test testm1::test_1 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 7 filtered out
```

# 11.3 Test Organization

概述：
- 测试是一门复杂的学科，不同的语言及不同的人对于测试会使用不同的术语和组织方式
- rust 将测试分为两大类：***unit test*** 和 ***integration test***
- ***unit test*** 可以测试 private 接口
- ***integration test*** 只能测试 public 接口

### Unit Test

##### 规则说明

1. unit test 关注的是独立的代码单元，通常是 module
2. 因此 unit test 针对的是具体某个代码单元的测试，测试时与其它代码单元也是隔离的
3. 代码单元一般遵循的规则是：每个 module 在 src 中单独使用一个代码文件，因此，unit test 也是在对应的每个代码单元文件中书写 test function
4. 因此，unit test 的一般书写规则是：在对应的代码单元文件中，创建一个 module，名称是 ```tests``` ，并将该 module 配置为 ```#[cfg(test)]```

##### ```#[cfg(test)]```

- ```#[cfg]``` 表示一些特定的配置选项
- 而 ```#[cfg(test)]``` 的意思是，这些代码仅用于测试
- 因此，只有 ```cargo test``` 的时候，rust 才会编译和运行 ```#[cfg(test)]``` 所标注的这些代码
- 同时，```cargo build``` 的时候，rust 不会编译和包含 ```#[cfg(test)]``` 所标注的代码，从而提高编译效率并缩小目标文件的大小
- 另一方面，正是由于 unit test 的代码位于各个代码单元文件中，从而为了让 rust 编译器能够区分开 unit test 代码，才需要 ```#[cfg(test)]``` 标注
- 最后，对于 integration test 来说，由于测试代码是独立位于不同的文件夹中，从而也就不需要 ```#[cfg(test)]``` 标注

回顾一下 unit test 代码：
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

##### Testing Private Functions

- 业界一直在争论是否应该允许直接测试 private function
- 但不管大家的测试理念如何，对 rust 来说，允许直接测试 private function

> 质疑

- 在 Chapter7 ，我用比较民间的语言对 pub 和 private 的进行了清晰的阐述
- 而在官方文档中，举了一个测试 private function 的例子，但是这个例子本身是符合 Chapter7 中的可见性规则的
- 而且，即使对于 unit test，同样也完全遵循 Chapter7 中的可见性规则
- 下面对拓展官方文档的例子进行扩展，来说明即使对于 test module，也没有打破 rust 本身的可见性规则
- 当然，也许官方文档想表达的并不是可见性规则，而是究竟是否应该直接测试 private function
- 可我的疑问是，既然遵循可见性规则，为什么要争论 private function 是否可以被测试

下面是官方文档的例子，本身是遵循 Chapter7 的可见性规则的：
```rust
fn funcg() {}

#[cfg(test)]
mod tests {
	use super::*;

    #[test]
    fn it_works() {
        //OK
        //可以测试funcg
        //虽然funcg是private
        funcg();
    }
}
```

同样的，根据 Chapter7 总结的可见性规则，下面的例子是不能被编译的：
```rust
mod sth {
	fn func() {}
}

#[cfg(test)]
mod tests {
	use super::*;

    #[test]
    fn it_works() {
        //ERROR
        //只能访问到sth
        //不能访问到sth中的func
        sth::func();
    }
}
```

### Integration Test

> 注：为了描述方便，我自己将 integration test 缩写为 ```IT``` ，不属于官方称呼

##### ```IT``` 组织规则

- IT 代码是完全位于 lib 之外的
- rust 将 lib 当做一个 crate ，然后将 IT 当做其它的 crate
- 也就是说，IT 需要访问 lib 中的功能时，需要使用 ```use libxxx```
- 由于 IT 与 lib 属于独立的两个 crate ，按照 Chapter7 的访问规则，IT 当然是访问不到 lib 中 private 的 item
- IT 的代码统一放在与 ```src``` 并列的 ```tests``` 目录下

##### ```tests``` 组织结构

- 在 ```tests``` 目录下，一个 ```rs``` 文件又是一个 crate ，这些独立的 crate 都通过 ```use libxxx``` 来访问 lib 中的功能
- 也就是说，各个 IT 是相互独立的，即使各个 IT 中的 function 和 module 同名
- 一个 ```rs``` 文件表示一个 IT ，在运行 ```cargo test``` 时，针对一个 IT ，会独立的描述该 IT 的测试清单，并为该 IT 统计测试结果

##### ```#[test]``` 标注

- 在一个 IT 中，test function 可以是独立的，也可以位于 module 之中
- 只要该 IT 中的任意位置的 function 被标注了 ```#[test]``` ，就会当做 test function
- 也就是说，对于 IT 来说，rust 关注的是对 test function 的 ```#[test]``` 标注，而不再需要对 module 标注 ```#[cfg(test)]```

##### ```IT``` 功能共享

- 首先要明确的是，在 ```tests``` 目录下，各个 IT 之间是相互独立的 crate ，因此，各个 ```rs``` 文件之间不会存在命名冲突，也无法共享功能
- 其次需要重复上面讲过的内容：在 ```tests``` 目录下，一个 ```rs``` 就是一个独立的 IT ，运行 ```cargo test``` 时会独立描述该 IT 的测试清单并统计测试结果，即使该 IT 中没有任何被标注为 ```#[test]``` 的 function
- 因此，如果针对各个 IT 之间需要共享一些功能代码，例如，将一些辅助功能进行整合，叫做 util ，则需要如下步骤：
    1. 在 ```tests``` 下建立 ```util``` 子目录
    2. 在 ```util``` 子目录下创建 ```mod.rs``` 文件里承载 util 的代码
    3. 在某个 IT 中需要使用 util 代码时，在对应该 IT 的 ```rs``` 文件中使用 ```mod util``` 语法
    4. 如果还有其它的共享功能需要整合，例如 help 系列，则重复上述步骤；
    5. 也就是说，子文件夹的名称决定了所共享的功能系列名称，也决定了在 IT 中 ```mod xxxx``` 的名称，同时，代码文件只能是 ```mod.rs``` 
    5. 如果需要将某个共享功能系列中的 ```mod.rs``` 代码继续拆分，则参考 Chapter7 对 module 的讲解
- 其实可以看到，上述全部步骤与 Chapter7 的 module 组织规则是一致的，也就是说，一个 IT 是一个 crate ，而一个 IT 又对应一个 ```rs``` ，从而，需要共享的功能代码对该 IT 来说是一种 sub module ，对应的，该 IT 中 需要使用 ```mod util``` ，而不是 ```use util```
- 另外，放在子目录中的共享功能不会被 ```cargo test``` 识别为 IT ，从而也就不会为该子目录的功能产生测试清单输出

##### IT/LIB 的逻辑关系

```
graph TD

A[libx] --> |use libx| B[IT1]
A --> |use libx| C[IT2]
B --> |mod util| D(util)
C --> |mod util| D
```

##### IT/LIB 的目录结构

```
graph TD

PJ{/libx} --> SRC{/src}
SRC --> LIB[lib.rs]
PJ --> TESTS{/tests}
TESTS --> IT1[it1.rs]
TESTS --> IT2[it2.rs]
TESTS --> UTIL{/util}
UTIL --> UTLSRC[mod.rs]
```

##### ```IT``` 例子展示

上述就是针对 integration test 的全部规则总结，下面通过例子，来逐步展示这些规则。

*++源码：lib_integ_test++*

> 创建 lib crate，名称是 lib_integ_test ，与 unit test 类似，lib.rs 代码如下：

```rust
//需要pub，否则IT访问不到
pub fn func_g() {}

//需要pub，否则IT访问不到
pub mod mod_g {
	pub fn func1() {}
}

#[cfg(test)]
mod tests {
	use super::*;

    #[test]
    fn unit_test1() {
    	mod_g::func1();
    }
}
```

> tests/iteg_test1.rs 代码如下，注意不管 function 是否在 module 中，只要是 test function ，就需要标注 #[test]：

```rust
//注意这句代码
use lib_integ_test;

#[test]
fn itg1_test1() {
    //访问lib中的function
	lib_integ_test::func_g();
}

mod itg1 {

    #[test]
    fn test1() {
        //访问lib中某个mod里的function
    	lib_integ_test::mod_g::func1();
    }
}
```

> 创建 util/mod.rs

```rust
/*
参考 Chapter7 ，
该文件所在的子文件夹名称是 util ，
因此 module 名称自动就是 util ，
所以，在该代码文件中，
所有的 mod 都是 util 的 submodule
*/

pub fn util_func1() {}

pub mod mod_u {
    pub fn func1() {}
}
```

> tests/iteg_test2.rs 代码如下，使用了 util 中的功能

```rust
//注意这句代码
mod util;

#[test]
fn itg2_test1() {
    //访问util中的function
	util::util_func1();
}

mod itg2 {

    #[test]
    fn test1() {
        //itg2是一个sub module
        //因此需要super::才能访问到util
    	super::util::mod_u::func1();
    }
}
```

> 下面是节选的部分测试结果，可以分别看到 unit test 、itg1/itg2 两个 integration test 的结果，同时，util 不会被测试。为了结果展示的清晰，我在每个 "Running ..." 之前，加了 ">>>" 标注。注意看每个 "Running ..." 的内容，其中展示了 IT 的名称。

```text
>>> Running target/debug/deps/lib_integ_test-801523445e71dcaa

running 1 test
test tests::unit_test1 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

>>> Running target/debug/deps/iteg_test1-07f5cf4a39a0f065

running 2 tests
test itg1::test1 ... ok
test itg1_test1 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

>>> Running target/debug/deps/iteg_test2-a8df2154fd340010

running 2 tests
test itg2::test1 ... ok
test itg2_test1 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

> 可以直接复制 tests/iteg_test1.rs 的内容来创建 tests/iteg_test3.rs ，且从运行结果可以看到各个 IT 之间不会产生命名冲突。

##### 关于 binary crate

- 对于 binary crate，如果只有 src/main.rs 而没有 src/lib.rs ，则不能进行 integration test
- 因为在 src/main.rs 中已经可以直接调用和测试代码